### PR TITLE
Net standard2.0

### PR DESCRIPTION
**Pull request by stepkillah**
update android nuget to fix java.lang.NullPointerException on latest xamarin

formatting fixes

### CODE REVIEW

**Comment by mrxten** [comment]
As I know for Xamarin libraries recommended .NET Standard version is 1.6.
Also my target support minimum of XF 2.5 sub-version. In your pull 2.5.1 isn't minimum.

Btw can you provide me info about java.lang.NullPointerException appeared at Android Support libraries ver. 25.4?

**Comment by stepkillah** [comment]
it throws this kind of exception, which is fixed by updating android packages

```java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mycompany.MyApp/md5f066c239292502fb4e67fb5be45f54ab.SplashActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.ContentFrameLayout.setId(int)' on a null object reference```

so, would you fix it?  or I should revert netstandard to 1.6 and xf 2.5 in this PR? 
btw, you could use multitarget to support both, 1.6 and 2.0

**Comment by mrxten** [comment]
Thx for contributing, but yes, I cannot merge branch with XF 2.5.1.

**Comment by mrxten** [comment]
Also, as I know, 2.0 support including 1.6 to project.

**Pull request closed without merging**
